services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "127.0.0.1:8432:80"
    environment:
      - "PGADMIN_DEFAULT_EMAIL=pgadmin@skipr.co"
      - "PGADMIN_DEFAULT_PASSWORD=admin"
    volumes:
      - "~/.config/pgadmin:/var/lib/pgadmin"
      # Ensure directory is writable by user ID 5050
      # See https://www.pgadmin.org/docs/pgadmin4/latest/container_deployment.html#mapped-files-and-directories
      - "~/Documents/pgAdmin:/var/lib/pgadmin/storage"
