version: "3.7"
services:
  mongo:
    container_name: skipr-mongo
    image: mongo
    ports:
      - "127.0.0.1:27017:27017"
    environment:
      - "MONGO_INITDB_DATABASE=pikaway"
    volumes:
      - "./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js"
      
  mongo-web:
    container_name: mongo-web
    image: mongo-express
    ports:
      - "127.0.0.1:8027:8081"
    environment:
      - "ME_CONFIG_MONGODB_SERVER=skipr-mongo"
    depends_on:
      - mongo

  micro-web:
    image: micro/micro
    container_name: skipr-micro-web
    command: web
    # network_mode: host
    ports:
      - "127.0.0.1:8082:8082"